server:
  port: 8083

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

spring:
  application:
    name: nopecho-streams
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    template:
      observation-enabled: true
    listener:
      observation-enabled: true